const state={page:'overview',mode:'dashboard',users:[{name:'Alessia Conti',sam:'aconti',department:'IT',ou:'OU=Tecnici,DC=demo,DC=local',status:'Abilitato'},{name:'Luca Ferri',sam:'lferri',department:'Amministrazione',ou:'OU=Uffici,DC=demo,DC=local',status:'Abilitato'},{name:'Marta Riva',sam:'mriva',department:'Risorse Umane',ou:'OU=Uffici,DC=demo,DC=local',status:'Disabilitato'},{name:'Paolo Greco',sam:'pgreco',department:'IT',ou:'OU=Tecnici,DC=demo,DC=local',status:'Abilitato'},{name:'Sara Villa',sam:'svilla',department:'Logistica',ou:'OU=Operativi,DC=demo,DC=local',status:'Abilitato'}]};
const pages={overview:'Panoramica',users:'Utenti',groups:'Gruppi',ous:'Unità organizzative',gpo:'Criteri GPO',tasks:'Attività pianificate'};const content=document.querySelector('#app-content');
function metric(a,b,c,d){return '<article class="metric"><div class="metric-top"><span>'+a+'</span><span class="metric-icon">'+d+'</span></div><div class="metric-value">'+b+'</div><div class="metric-note">'+c+'</div></article>'}
function overview(){return '<div class="welcome"><div><h2>Buongiorno, Mattia</h2><p>Riepilogo dell’ambiente e accesso alle operazioni più utilizzate.</p></div><span class="date-chip">AMBIENTE DIMOSTRATIVO</span></div><div class="metrics">'+metric('Utenti censiti','1.284','Directory di esempio','♙')+metric('Gruppi','86','Oggetti dimostrativi','♧')+metric('Unità organizzative','24','Struttura simulata','▤')+metric('GPO','32','Criteri di esempio','⚙')+'</div><div class="columns"><section class="panel"><div class="panel-head"><div><h3>Attività recenti</h3><div class="panel-sub">Eventi simulati a scopo dimostrativo</div></div><button class="text-button" data-page="users">Apri utenti →</button></div><div class="activity"><div class="activity-row"><div class="activity-icon">⌕</div><div class="activity-copy"><strong>Ricerca utente completata</strong><small>aconti · Unità IT</small></div><span class="activity-time">09:42</span></div><div class="activity-row"><div class="activity-icon">♙</div><div class="activity-copy"><strong>Account disabilitato</strong><small>mriva · Operazione dimostrativa</small></div><span class="activity-time">09:18</span></div><div class="activity-row"><div class="activity-icon">⚙</div><div class="activity-copy"><strong>Analisi criteri GPO</strong><small>Workstation-Base · Nessuna modifica</small></div><span class="activity-time">Ieri</span></div></div></section><section class="panel"><div class="panel-head"><div><h3>Accesso rapido</h3><div class="panel-sub">Seleziona un’area di lavoro</div></div></div><div class="quick-grid"><button class="quick" data-page="users"><span>♙</span><strong>Gestione utenti</strong><small>Cerca e consulta account</small></button><button class="quick" data-page="groups"><span>♧</span><strong>Gruppi</strong><small>Consulta appartenenze</small></button><button class="quick" data-page="ous"><span>▤</span><strong>Esplora OU</strong><small>Visualizza la struttura</small></button><button class="quick" data-page="gpo"><span>⚙</span><strong>Analisi GPO</strong><small>Consulta i criteri</small></button></div><div class="notice">Modalità prototipo: i dati sono fittizi. Nessuna operazione viene eseguita su Active Directory.</div></section></div>'}
function users(){return '<div class="page-toolbar"><div class="panel-sub">Elenco di account fittizi per validare ricerca e visualizzazione.</div><input class="search" id="user-search" placeholder="Cerca per nome, account o reparto…" aria-label="Cerca utenti"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Nome</th><th>Account</th><th>Reparto</th><th>Unità organizzativa</th><th>Stato</th></tr></thead><tbody id="user-rows"></tbody></table></div><div class="notice">Consultazione simulata. Ricerca e modifiche AD reali non sono ancora collegate.</div>'}
const records={groups:[['Domain Admins','Gruppo di sicurezza','12'],['Helpdesk Tier 1','Gruppo di sicurezza','8'],['HR-Staff','Gruppo di sicurezza','24']],ous:[['Tecnici','OU=Tecnici,DC=demo,DC=local','42'],['Uffici','OU=Uffici,DC=demo,DC=local','108'],['Operativi','OU=Operativi,DC=demo,DC=local','73']],gpo:[['Workstation-Base','Collegata','OU=Workstations'],['Password-Policy','Collegata','Dominio'],['Helpdesk-Restrictions','Non collegata','—']],tasks:[['AD-HealthCheck','Giornaliera · 06:00','Pronta'],['Log-Cleanup','Settimanale · Domenica','Pronta'],['Inventory-Sync','Ogni 4 ore','Disabilitata']]};
function simplePage(p){const c={groups:['Gruppi','Nome','Tipo','Membri'],ous:['OU','Nome OU','Percorso','Oggetti'],gpo:['GPO','Nome criterio','Collegamento','Destinazione'],tasks:['Attività','Attività','Pianificazione','Stato']}[p];return '<div class="page-toolbar"><div class="panel-sub">Dati dimostrativi · sola visualizzazione</div></div><div class="table-wrap"><table class="data-table"><thead><tr>'+c.slice(1).map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+records[p].map(r=>'<tr>'+r.map((v,i)=>'<td>'+(i===r.length-1&&p==='tasks'?'<span class="pill '+(v==='Pronta'?'ok':'warn')+'">'+v+'</span>':v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><div class="notice">I dati mostrati non provengono da un dominio reale. Le operazioni sono disabilitate.</div>'}
function guided(){return '<section class="panel guided-card"><div class="step-count">PERCORSO GUIDATO · INTRODUZIONE</div><h2>Che cosa vuoi fare?</h2><p>La modalità guidata accompagna l’operatore attraverso procedure controllate. In questo prototipo puoi esplorare i flussi senza modificare dati reali.</p><div class="workflow-list"><button class="workflow" data-page="users"><b>01</b><span><strong>Consultare un account</strong><small>Ricerca e visualizzazione dei dettagli</small></span></button><button class="workflow" data-page="groups"><b>02</b><span><strong>Verificare un gruppo</strong><small>Informazioni e appartenenze</small></span></button><button class="workflow" data-page="ous"><b>03</b><span><strong>Esplorare la struttura OU</strong><small>Individuazione di unità e oggetti</small></span></button><button class="workflow" data-page="gpo"><b>04</b><span><strong>Analizzare un criterio GPO</strong><small>Criteri e collegamenti</small></span></button></div><button class="primary" data-page="overview">Torna alla panoramica</button></section>'}
function drawUsers(q){const rows=state.users.filter(u=>Object.values(u).some(v=>v.toLowerCase().includes(q.toLowerCase())));document.querySelector('#user-rows').innerHTML=rows.map(u=>'<tr><td>'+u.name+'</td><td>'+u.sam+'</td><td>'+u.department+'</td><td>'+u.ou+'</td><td><span class="pill '+(u.status==='Abilitato'?'ok':'warn')+'">'+u.status+'</span></td></tr>').join('')||'<tr><td colspan="5" class="empty">Nessun utente corrispondente.</td></tr>'}
function render(){document.querySelector('#page-title').textContent=state.mode==='guided'?'Modalità guidata':pages[state.page];content.innerHTML=state.mode==='guided'?guided():state.page==='overview'?overview():state.page==='users'?users():simplePage(state.page);content.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>{state.page=el.dataset.page;state.mode='dashboard';document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));render()}));if(state.page==='users'&&state.mode==='dashboard'){drawUsers('');document.querySelector('#user-search').addEventListener('input',e=>drawUsers(e.target.value))}}
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));render()}));document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{state.page=b.dataset.page;state.mode='dashboard';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));render()}));render();

// Bridge desktop: il browser normale resta in modalità demo, WebView2 interroga solo operazioni consentite.
if (window.chrome && window.chrome.webview) {
  window.chrome.webview.addEventListener('message', event => {
    const result = event.data;
    const label = document.querySelector('#connection-label');
    if (result && result.mode && label) label.textContent = 'Backend locale · ' + result.mode;
    if (result && result.error && label) label.textContent = 'Backend non disponibile';
  });
  window.chrome.webview.postMessage({ operation: 'status' });
}
